import type { Metadata } from 'next';
import Link from 'next/link';
import { HomeNavbar } from '@/components/HomeNavbar';

export const metadata: Metadata = {
  title: 'Terms of Service — Crelyzor',
  description: 'Read the Crelyzor Terms of Service.',
};

const LAST_UPDATED = 'April 22, 2025';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
      <HomeNavbar />

      <main className="max-w-3xl mx-auto px-5 sm:px-8 pt-32 pb-24">
        <p className="text-xs font-semibold tracking-widest uppercase text-muted-foreground mb-4">
          Legal
        </p>
        <h1 className="text-4xl font-semibold tracking-tight text-foreground mb-3">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-12">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none text-sm leading-relaxed space-y-8 text-foreground/80">
          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Crelyzor (&ldquo;Service&rdquo;), you agree
              to be bound by these Terms of Service. If you do not agree, please
              do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              2. Description of Service
            </h2>
            <p>
              Crelyzor is a productivity platform that provides meeting
              transcription, AI summaries, task management, digital business
              cards, and scheduling tools. Features and availability may change
              at any time.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              3. User Accounts
            </h2>
            <p>
              You must sign in with a valid Google account. You are responsible
              for maintaining the confidentiality of your account and all
              activity under it. You must notify us immediately of any
              unauthorised use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              4. Acceptable Use
            </h2>
            <p>
              You agree not to misuse the Service. This includes, but is not
              limited to: uploading illegal content, attempting to
              reverse-engineer the platform, using the Service to harass others,
              or circumventing usage limits.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              5. Intellectual Property
            </h2>
            <p>
              All content generated by you (meeting recordings, notes, cards)
              remains yours. Crelyzor retains all rights to the platform,
              design, and underlying technology.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              6. Subscriptions & Billing
            </h2>
            <p>
              Free plan features are provided at no cost. Paid plans are billed
              as described on the Pricing page. We reserve the right to change
              pricing with 30 days&apos; notice. No refunds are provided for
              partial billing periods.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              7. Termination
            </h2>
            <p>
              We may suspend or terminate your account for violations of these
              Terms. You may delete your account at any time from Settings. Upon
              termination, your data will be deleted within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              8. Disclaimer of Warranties
            </h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of
              any kind. We do not guarantee that the Service will be
              uninterrupted, error-free, or meet your specific requirements.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              9. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, Crelyzor shall not be
              liable for any indirect, incidental, or consequential damages
              arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              10. Changes to Terms
            </h2>
            <p>
              We may update these Terms at any time. Continued use of the
              Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">
              11. Contact
            </h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a
                href="mailto:support@crelyzor.com"
                className="underline underline-offset-2 hover:text-foreground transition-colors"
              >
                support@crelyzor.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-border flex items-center gap-6">
          <Link
            href="/privacy"
            className="text-xs text-muted-foreground hover:text-foreground transition-colors underline underline-offset-2"
          >
            Privacy Policy
          </Link>
          <Link
            href="/"
            className="text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
